- id: ansible_doctor
  name: Ansible doctor
  description: Inserts tags documentation into README.md (using ansible-doctor).
  require_serial: false
  language: python
  entry: ansible-doctor -f .
  pass_filenames: false
  types: []
  files: \.y?ml$
  exclude_types: [xml]
  exclude: >
          (?x)^(
          .+.iml |
          .+.gitignore |
          \.gitlab-ci.*$ |
          .+\.idea\/.*$ |
          \.pre-commit.*$ |
          requirements.*$
          )$
